def Wells_A_B_Selected_Standard():

  Aliases.Quantist.MainWindowView.Activate()
  aqObject.CheckProperty(NameMapping.Sys.Quantist.HwndSource_MainWindowView2.MainWindowView.DockPanel.Grid.Border2.ContentControl.ContentListView.DynamicGridControl.WellAssignmentsViewModel_af21aa09c2d844d199e7e61d8427c074.WellAssignmentsView.Grid.PlatesViewScrollViewer.ItemsControl.ContentPresenter.Plate96WellView.Border, "VisibleOnScreen", cmpEqual, True)
  LLCollection1.Wells_A_B_Selected_Standard.Execute(NameMapping.Sys.Quantist.HwndSource_MainWindowView2.MainWindowView.DockPanel.Grid.Border2.ContentControl.ContentListView.DynamicGridControl.WellAssignmentsViewModel_af21aa09c2d844d199e7e61d8427c074.WellAssignmentsView.Grid.PlatesViewScrollViewer)
  ProjectSuite.Variables.Short_Delay
  Regions.Wells_A_B_Selected_Standard.Check(NameMapping.Sys.Quantist.HwndSource_MainWindowView2.MainWindowView.DockPanel.Grid.Border2.ContentControl.ContentListView.DynamicGridControl.WellAssignmentsViewModel_af21aa09c2d844d199e7e61d8427c074.WellAssignmentsView.Grid.PlatesViewScrollViewer.ItemsControl.ContentPresenter.Plate96WellView.Border)

  LLCollection1.Wells_C_Selected_Unknown.Execute(NameMapping.Sys.Quantist.HwndSource_MainWindowView2.MainWindowView.DockPanel.Grid.Border2.ContentControl.ContentListView.DynamicGridControl.WellAssignmentsViewModel_af21aa09c2d844d199e7e61d8427c074.WellAssignmentsView.Grid.PlatesViewScrollViewer.ItemsControl.ContentPresenter.Plate96WellView.Border)
  
def  Wells_C_Selected_Unknown():

  aqObject.CheckProperty(NameMapping.Sys.Quantist.HwndSource_MainWindowView2.MainWindowView.DockPanel.Grid.Border2.ContentControl.ContentListView.DynamicGridControl.WellAssignmentsViewModel_af21aa09c2d844d199e7e61d8427c074.WellAssignmentsView.Grid.PlatesViewScrollViewer.ItemsControl.ContentPresenter.Plate96WellView.Border, "VisibleOnScreen", cmpEqual, True)
  LLCollection1.Wells_C_Selected_Unknown.Execute(NameMapping.Sys.Quantist.HwndSource_MainWindowView2.MainWindowView.DockPanel.Grid.Border2.ContentControl.ContentListView.DynamicGridControl.WellAssignmentsViewModel_af21aa09c2d844d199e7e61d8427c074.WellAssignmentsView.Grid.PlatesViewScrollViewer.ItemsControl.ContentPresenter.Plate96WellView.Border)
  ProjectSuite.Variables.Short_Delay
  
